<%
Const FontStyleRegular    = 0
Const FontStyleBold       = 1
Const FontStyleItalic     = 2
Const FontStyleUnderline  = 4
Const FontStyleStrikeout  = 8

Const StringAlignmentNear   = 0
Const StringAlignmentCenter = 1
Const StringAlignmentFar    = 2

Const ItpModeBicubic         = 0
Const ItpModeBilinear        = 1
Const ItpModeNearestNeighbor = 2

Const Ok                        = 0
Const GenericError              = 1
Const InvalidParameter          = 2
Const OutOfMemory               = 3
Const ObjectBusy                = 4
Const InsufficientBuffer        = 5
Const NotImplemented            = 6
Const Win32Error                = 7
Const WrongState                = 8
Const Aborted                   = 9
Const FileNotFound              = 10
Const ValueOverflow             = 11
Const AccessDenied              = 12
Const UnknownImageFormat        = 13
Const FontFamilyNotFound        = 14
Const FontStyleNotFound         = 15
Const NotTrueTypeFont           = 16
Const UnsupportedGdiplusVersion = 17
Const GdiplusNotInitialized     = 18
Const PropertyNotFound          = 19
Const PropertyNotSupported      = 20
Const ProfileNotFound           = 21

Const PropertyTagImageDescription = 270
Const PropertyTagEquipMake        = 271
Const PropertyTagEquipModel       = 272
Const PropertyTagExifShutterSpeed = 37377
Const PropertyTagExifFNumber      = 33437
Const PropertyTagExifFocalLength  = 37386
Const PropertyTagExifExposureTime = 33434
Const PropertyTagExifISOSpeed     = 34855
Const PropertyTagExifDTOrig       = 36867
Const PropertyTagExifUserComment  = 37510

Const TextRenderingHintSystemDefault            = 0     ' Glyph with system default rendering hint
Const TextRenderingHintSingleBitPerPixelGridFit = 1     ' Glyph bitmap with hinting
Const TextRenderingHintSingleBitPerPixel        = 2     ' Glyph bitmap without hinting
Const TextRenderingHintAntiAliasGridFit         = 3     ' Glyph anti-alias bitmap with hinting
Const TextRenderingHintAntiAlias                = 4     ' Glyph anti-alias bitmap without hinting
Const TextRenderingHintClearTypeGridFit         = 5		' Glyph CT bitmap with hinting
%>